export const widgetLogo = {
  appleMusic: require('./link/apple-music.png'),
  amazon: require('./link/amazon.png'),
  applePodcast: require('./link/apple-podcast.png'),
  appStore: require('./link/appstore.png'),
  article: require('./link/article.png'),
  depop: require('./link/depop.png'),
  facebook: require('./social/facebook.png'),
  instagram: require('./social/instagram.png'),
  poshmark: require('./link/poshmark.png'),
  snapchat: require('./social/snapchat.png'),
  spotify: require('./link/spotify.png'),
  soundcloud: require('./link/soundcloud.png'),
  tiktok: require('./video/tiktok.png'),
  twitch: require('./video/twitch.png'),
  twitter: require('./social/twitter.png'),
  youtube: require('./video/youtube.png'),
  etsy: require('./link/etsy.png'),
  website: require('./link/website.png'),
  depopLogo: require('./link/depopLogo.png'),
  amazonLogo: require('./link/amazonLogo.png'),
  etsyLogo: require('./link/etsyLogo.png'),
  podcastLogo: require('./link/podcastLogo.png'),
  appStoreLogo: require('./link/appStoreLogo.png'),
  clickCount: require('./link/clickCount.png'),
};
